rmcs_executor:
  ros__parameters:
    update_rate: 1000.0
    components:
      - rmcs_core::hardware::mycboard -> cboard_example
      - rmcs_core::angle::anglecalculator -> anglecalculator
      - rmcs_core::example::RemoteControllerExample -> remote_controller
      
      - rmcs_core::controller::pid::PidController -> dr16_leftmotor_basic_torque_pid
      - rmcs_core::controller::pid::PidController -> dr16_rightmotor_basic_torque_pid
      - rmcs_core::controller::pid::PidController -> roll_0_controller_pid

      - rmcs_core::controller::pid::PidController -> target_pitch_angle_control_velocity_pid
      - rmcs_core::controller::pid::PidController -> target_pitch_left_control_velocity_pid
      - rmcs_core::controller::pid::PidController -> target_pitch_left_control_velocity_pid

      - rmcs_core::example::dr16finaltorque -> dr16finaltorque
      - rmcs_core::example::pitchcontrolltorque -> targetfinaltorque
      - rmcs_core::example::info -> info
cboard_example:
  ros__parameters:
    usb_pid: -1

target_pitch_angle_control_velocity_pid:
  ros__parameters: 
    measurement: /dragon/pitch/angle
    setpoint: 28
    control: /target/pitch/aim/velocity
    kp: 10.0
    ki: 0.0
    kd: 0.0

target_pitch_left_control_velocity_pid:
  ros__parameters: 
    measurement: /example/left2006/velocity
    setpoint: /target/pitch/aim/velocity
    control: /target/pitch/left/basic/torque
    kp: 10.0
    ki: 0.0
    kd: 0.0


target_pitch_right_control_velocity_pid:
  ros__parameters: 
    measurement: /example/right2006/velocity
    setpoint: /target/pitch/aim/velocity
    control: /target/pitch/right/basic/torque
    kp: 10.0
    ki: 0.0
    kd: 0.0


dr16_leftmotor_basic_torque_pid:
  ros__parameters: 
    measurement: /example/left2006/velocity
    setpoint: /example/dr16/aim_velocity
    control: /example/dr16/left2006/basictorque
    kp: 10.0
    ki: 0.0
    kd: 0.0
dr16_rightmotor_basic_torque_pid:
  ros__parameters:
    measurement: /example/right2006/velocity
    setpoint: /example/dr16/aim_velocity
    control: /example/dr16/right2006/basictorque
    kp: 10.0
    ki: 0.0
    kd: 0.0
roll_0_controller_pid:
  ros__parameters:
    measurement: dragon/roll/angle
    setpoint: 0.0
    control: roll/angle/basictorque
    kp: 0.0
    ki: 0.0
    kd: 0.0
anglecalculator:
  ros__parameters:
    {}
remote_controller:
  ros__parameters:
    {}
dr16finaltorque:
  ros__parameters:
    {}
targetfinaltorque:
  ros__parameters:
    {}
info:
  ros__parameters:
    {}