rmcs_executor:
  ros__parameters:
    update_rate: 1000.0
    components:
      - rmcs_core::hardware::DeviceExample -> cboard_example
      - rmcs_core::example::RemoteControllerExample -> remote_control_message
      - rmcs_core::controller::pid::PidController -> M2006_velicity_controller


cboard_example:
  ros__parameters:
    usb_pid: -1

M2006_velicity_controller:
  ros__parameters:
    setpoint: /example/M2006/control_velocity
    measurement: /example/M2006/velocity
    control: /example/M2006/control_torque
    kp: 10.0
    ki: 0.0
    kd: 0.0
broadcaster:
  ros__parameters:
    forward_list:
     - /example/M2006/control_velocity

remote_control_message:
  ros__parameters:
    {}