rmcs_executor:
  ros__parameters:
    update_rate: 1000.0
    components:
      - rmcs_core::hardware::WheelLegInfantry -> infantry_hardware

infantry_hardware:
  ros__parameters:
    board_serial_bottom_board: "D4-818D-A833-2048-9829-303A-126D"
